dist: xenial
language: elixir
#cache: apt
# services:
#   - mysql
before_script:
  - wget https://repo.mysql.com//mysql-apt-config_0.8.24-1_all.deb
  - sudo dpkg -i mysql-apt-config_0.8.24-1_all.deb
  - sudo apt-get update -q || true
  - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
  - sudo systemctl restart mysql
  - sudo mysql_upgrade
  - mysql --version
  - mysql -e 'CREATE DATABASE mailgun_logger_ci_test;'
matrix:
  include:
    - elixir: 1.13
      otp_release: 24.0
notifications:
  recipients:
    - randy@jackjoe.be
